//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entidades
{
    using System;
    using System.Collections.Generic;
    
    public partial class Vehicle
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Vehicle()
        {
            this.Sales = new HashSet<Sale>();
        }
    
        public string vinVehicle { get; set; }
        public string numberPatent { get; set; }
        public string brand { get; set; }
        public string line { get; set; }
        public string model { get; set; }
        public Nullable<int> doors { get; set; }
        public Nullable<bool> gps { get; set; }
        public string typeVehicle { get; set; }
        public string classVehicle { get; set; }
        public string status { get; set; }
        public Nullable<double> price { get; set; }
        public System.DateTime dateAdmission { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sale> Sales { get; set; }
    }
}
